[versions]
# Plugins
indraSpotless = "3.1.3"
nexusPublishPlugin = "2.0.0"

lettuce = "6.5.5.RELEASE"
slf4jApi = "2.0.17"
annotations = "24.0.0"

# Tests
jedisMock = "1.1.9"
slf4jSimple = "2.0.17"

[libraries]
lettuce = { group = "io.lettuce", name = "lettuce-core", version.ref = "lettuce" }
slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jApi" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations"}

# Tests
jedisMock = { group = "com.github.fppt", name = "jedis-mock", version.ref = "jedisMock" }
sl4jSimple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4jSimple" }

[plugins]
indraSpotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indraSpotless"}
nexusPublishPlugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublishPlugin" }